"""add_customers_shifts_inventory_suppliers_promotions

Revision ID: 897bc81f39b9
Revises: 842eee561565
Create Date: 2026-04-13 22:29:07.451522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897bc81f39b9'
down_revision: Union[str, None] = '842eee561565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('promotions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', 'BOGO', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scope', sa.Enum('ORDER', 'PRODUCT', 'CATEGORY', name='promoscope'), nullable=False),
    sa.Column('scope_target_ids', sa.Text(), nullable=True),
    sa.Column('min_order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_customer', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=False)
    op.create_index(op.f('ix_promotions_tenant_id'), 'promotions', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('RECOUNT', 'DAMAGE', 'THEFT', 'RETURN', 'TRANSFER_IN', 'TRANSFER_OUT', 'OPENING_STOCK', 'OTHER', name='adjustmentreason'), nullable=False),
    sa.Column('qty_before', sa.Integer(), nullable=False),
    sa.Column('qty_change', sa.Integer(), nullable=False),
    sa.Column('qty_after', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_adjustments_product_id'), 'inventory_adjustments', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_tenant_id'), 'inventory_adjustments', ['tenant_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ORDERED', 'RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_table('shifts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('cashier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='shiftstatus'), nullable=False),
    sa.Column('opening_float', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_variance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_location_id'), 'shifts', ['location_id'], unique=False)
    op.create_index(op.f('ix_shifts_status'), 'shifts', ['status'], unique=False)
    op.create_index(op.f('ix_shifts_tenant_id'), 'shifts', ['tenant_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('txn_type', sa.Enum('EARN', 'REDEEM', 'ADJUST', 'EXPIRE', name='loyaltytxntype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_customer_id'), 'loyalty_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_tenant_id'), 'loyalty_transactions', ['tenant_id'], unique=False)
    op.create_table('promo_usages',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_usages_promotion_id'), 'promo_usages', ['promotion_id'], unique=False)
    op.add_column('orders', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('shift_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('promo_discount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('loyalty_discount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('loyalty_points_earned', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('loyalty_points_redeemed', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'loyalty_points_redeemed')
    op.drop_column('orders', 'loyalty_points_earned')
    op.drop_column('orders', 'loyalty_discount')
    op.drop_column('orders', 'promo_discount')
    op.drop_column('orders', 'shift_id')
    op.drop_column('orders', 'customer_id')
    op.drop_index(op.f('ix_promo_usages_promotion_id'), table_name='promo_usages')
    op.drop_table('promo_usages')
    op.drop_index(op.f('ix_loyalty_transactions_tenant_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_customer_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_shifts_tenant_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_status'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_location_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_inventory_adjustments_tenant_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_product_id'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_promotions_tenant_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
